name: Netlify Production Deploy

on:
  release:
    types: [released]

jobs:
  netlify-prod-deploy:
    name: Netlify Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node v14
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build React WebApp
        run: yarn run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Production Deploy - ${{ github.event.release.name }}
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          enable-commit-status: false

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
